name: release
on: [create, workflow_dispatch]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: npm publish
        run: npm publish --access public
        working-directory: /
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
